import { Injectable } from '@angular/core';
// Generated by https://quicktype.io

export interface ProductResponse {
  products: Product[];
  total:    number;
  skip:     number;
  limit:    number;
}

export interface CartResponse {
  carts: Cart[];
  total: number;
  skip:  number;
  limit: number;
}

export interface Cart {
  id:              number;
  products:        Product[];
  total:           number;
  discountedTotal: number;
  userId:          number;
  totalProducts:   number;
  totalQuantity:   number;
}

export interface Product {
  id:                  number;
  brand?:              string;
  category?:           string;
  description?:        string;
  discountPercentage?: number;
  images?:             string[];
  price?:              number;
  quantity?:           number;
  rating?:             number;
  stock?:              number;
  thumbnail?:          string;
  title?:              string;
  total?:              number;
}

@Injectable({
  providedIn: 'root'
})
export class ConstantsService {

  public BASE_URL = "https://dummyjson.com"

  public PRODUCTS_URL = this.BASE_URL + "/products";
  public CARTS_URL = this.BASE_URL + "/carts";


  constructor() { }

}
